# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app.mysql:
        class: AppBundle\Libs\MySQL\MySQLDriver

    app.elastic:
        class: AppBundle\Libs\ElasticSearch\ElasticSearchDriver

    app.productRepository:
        class: AppBundle\Libs\Product\ProductRepository
        arguments: ['@app.mysql', '@app.elastic']
